### PR TITLE
Bot folder management system, plus more reliable shortcut

### PR DESCRIPTION
**Pull request by tarehart**
image

The new shortcut command works for me, and also worked for somebody that had problems with the old one.

### CODE REVIEW

**Comment by skyborgff** [comment]
I'm getting this error

`C:\Users\fabio\fabio\Software\Programing\RLBot\RLBotGUI>python run.py
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    gui.start()
  File "C:\Users\fabio\fabio\Software\Programing\RLBot\RLBotGUI\rlbot_gui\gui.py", line 258, in start
    if not is_chrome_installed():
  File "C:\Users\fabio\fabio\Software\Programing\RLBot\RLBotGUI\rlbot_gui\gui.py", line 250, in is_chrome_installed
    return eel.browsers.chr.get_instance_path() is not None
AttributeError: module 'eel.browsers' has no attribute 'chr'`

**Comment by skyborgff** [comment]
Im using 3.6.8, that may be the issue

**Comment by skyborgff** [comment]
using 3.7 gives the same issue

**Comment by tarehart** [comment]
From eldest:

>oh i know
what eel version you are using locally
cause the newest have changed some stuff
you should be able to go to the file on which the error is caused and on that line change chr to chm or downgrade eel version for now

We should probably pin eel to a specific version number

**Comment by skyborgff** [comment]
or change chr to chm

**Comment by tarehart** [comment]
I think we need to pin eel because after people install RLBotGUI, eel does not upgrade itself, so they're probably stuck with the old version.

I think the only way around that would be to add eel as a dependency inside setup.py, but installing / upgrading packages using that technique tends to break a lot for some reason.

**Comment by tarehart** [comment]
Oh, I forgot - we can't even pin Eel to a version, you actually need to pull my disable-cache branch and install the local version in pip https://github.com/tarehart/Eel/tree/disable-cache

That's a bit of a mess, sorry. It's got nothing to do with these latest changes though, so I want to push em

**Comment by IamEld3st** [comment]
Approved and merging eel version problems will be fixed in later pr.

**Comment by tarehart** [comment]
Thanks! I just deployed to pypi and uploaded the new installer to Google Drive.

**Pull request merged**
